### ISSUE TITLE
Crashes with obsure VS Code Error model

### ISSUE THREAD

**Issue by bcdady** [dannywrayuk/yaml-2-json-vscode#1]
Repro
I saved a .json file (with content from a functional Grafana dashboard, and then opened the menu and selected to toggle to YAML. The tab/file closed, and an error was displayed.

<img width="464" alt="image" src="https://user-images.githubusercontent.com/2688689/229390086-12d364e8-6a0d-4b04-b2c2-80d04df6747b.png">

**Comment by dannywrayuk** [comment]
Hey, 

I appreciate you taking the time to open an issue! Though I'm going to struggle to fix the error without a reproducible example.

The error you're seeing is coming from this section of code [here](https://github.com/dannywrayuk/yaml-json-converter/blob/master/src/extension.ts#L54). So there is a chance that it could be a write permissions issue? Otherwise I can't help unless I can reproduce this myself to debug.

It's worth noting that this extension served as more of a learning tool when i first got into extension development, hence why the error messaging is rough around the edges. I think I might add a settings toggle to turn off some of the more flaky features I tried to add (YAML anchor interoperability with JSON) and it _might_ be enough to fix the problem for you.

**Comment by dannywrayuk** [comment]
[Release v0.0.15](https://github.com/dannywrayuk/yaml-json-converter/releases/tag/v0.0.15) Has better error logging and a settings option that might help you out. Let me know how you get on :)
